# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gSDk6byGEnr8OVUY9G5-FyqAh4EOzr_a
"""

# import packages
import numpy as np
import torch, os, random
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as F
from time import time
from sklearn.preprocessing import StandardScaler
import pytorch_lightning as pl

# fixed random seed
start = time()
torch.manual_seed(123)
torch.cuda.manual_seed(123)
np.random.seed(123)
random.seed(123)
torch.backends.cudnn.enabled = False
torch.backends.cudnn.deterministic = True
# use cuda
if torch.cuda.is_available() == True:
    device = "cuda"
    print("Use GPU!")
else:
    device = "cpu"


# # load dataset
# # 記得改回traindata.npy
testdata = np.load("./testdata.npy")

norm = True
if norm:
    print("preprocessing data")
    scalerA = StandardScaler()
    scalerA.fit(testdata[:,0,:])
    # scalerA.fit(traindata[:,0,:])
    # tmp = scalerA.transform(traindata[:,0,:])
    # traindata[:,0,:] = tmp
    tmp = scalerA.transform(testdata[:,0,:])
    testdata[:,0,:] = tmp
    scalerB = StandardScaler()
    scalerB.fit(testdata[:,1,:])
    # scalerB.fit(traindata[:,1,:])
    # tmp = scalerB.transform(traindata[:,1,:])
    # traindata[:,1,:] = tmp
    tmp = scalerB.transform(testdata[:,1,:])
    testdata[:,1,:] = tmp

testdata = np.fft.fft(testdata)

# define dataset here
class RawDataset(Dataset):
    def __init__(self, traindata, trainlabel):
        self.traindata = torch.from_numpy(np.array(traindata).astype(np.float32))
        if trainlabel is not None:
            self.trainlabel = torch.from_numpy(np.array(trainlabel).astype(np.int64))
        else:
            self.trainlabel = None
    def __len__(self):
        return len(self.traindata)
    def __getitem__(self,idx):
        sample = self.traindata[idx]
        if self.trainlabel is not None:
            target = self.trainlabel[idx]
            return sample, target
        else:
            return sample

testset = RawDataset(testdata,None)
testloader = DataLoader(testset,batch_size=1,shuffle=False)

# construct model__CNN_v4
class MyDSPNet(pl.LightningModule):
    def __init__(self):
        super().__init__()
        # define your arch
        self.encoder = nn.Sequential(
            nn.Conv1d(2,16,kernel_size=16,stride=8,padding=0),
            nn.ReLU(),
            nn.MaxPool1d(kernel_size=4), # 取最大值

            nn.Conv1d(16,64,kernel_size=12,stride=4,padding=0),
            nn.ReLU(),
            nn.MaxPool1d(kernel_size=2), # 取最大值

            nn.Conv1d(64,128,kernel_size=4,stride=2,padding=0),
        )

        self.clf = nn.Linear(3712, 3)

    def forward(self, x):
        # define your forward
        x = self.encoder(x)
        x = x.view(x.size(0),-1)
        output = self.clf(x)
        return output
    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=3e-3)
        return optimizer
    def training_step(self, train_batch, batch_idx):
        x, y = train_batch
        output = self(x)
        loss = F.cross_entropy(output, y)
        self.log('train_loss', loss)
        return loss

model = MyDSPNet()
# model = load_state_dict(torch.load("./weight.pt"))
model.load_state_dict(torch.load("./weight.pt",map_location=device))
model.eval()

# output prediction
model.to(device)
with open("result.csv","w") as f:
    f.write("id,category\n")
    for i, x in enumerate(testloader):
        x = x.to(device)
        output = model(x)
        pred = output.argmax(dim=1, keepdim=True)
        f.write("%d,%d\n"%(i,pred.item()))
